using MailClient.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using NpgsqlTypes;

namespace MailClient.Infrastructure.Persistence;

public sealed class AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
{
    public DbSet<MailAccount> MailAccounts => Set<MailAccount>();
    public DbSet<MailCredential> MailCredentials => Set<MailCredential>();
    public DbSet<MailSession> MailSessions => Set<MailSession>();
    public DbSet<MailFolder> MailFolders => Set<MailFolder>();
    public DbSet<MailClient.Domain.Entities.Mail> Mails => Set<MailClient.Domain.Entities.Mail>();
    public DbSet<Attachment> Attachments => Set<Attachment>();
    public DbSet<SyncState> SyncStates => Set<SyncState>();
    public DbSet<SyncSkippedUid> SyncSkippedUids => Set<SyncSkippedUid>();
    public DbSet<SendOperation> SendOperations => Set<SendOperation>();
    public DbSet<DeviceToken> DeviceTokens => Set<DeviceToken>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<Conversation> Conversations => Set<Conversation>();
    public DbSet<MailParticipant> Participants => Set<MailParticipant>();
    public DbSet<MailClient.Domain.Entities.MailHeader> MailHeaders => Set<MailClient.Domain.Entities.MailHeader>();
    public DbSet<RuntimeConfiguration> RuntimeConfigurations => Set<RuntimeConfiguration>();
    public DbSet<OAuthStateNonce> OAuthStateNonces => Set<OAuthStateNonce>();
    public DbSet<AllowlistedEmail> AllowlistedEmails => Set<AllowlistedEmail>();
    public DbSet<ScheduledSend> ScheduledSends => Set<ScheduledSend>();
    public DbSet<ScheduledSendAttachment> ScheduledSendAttachments => Set<ScheduledSendAttachment>();
    public DbSet<MailLabel> MailLabels => Set<MailLabel>();
    public DbSet<MailRule> MailRules => Set<MailRule>();
    public DbSet<MailLabelAssignment> MailLabelAssignments => Set<MailLabelAssignment>();
    public DbSet<MailSnooze> MailSnoozes => Set<MailSnooze>();
    public DbSet<PinnedMail> PinnedMails => Set<PinnedMail>();
    public DbSet<Contact> Contacts => Set<Contact>();
    public DbSet<MailTemplate> MailTemplates => Set<MailTemplate>();
    public DbSet<MailSnippet> MailSnippets => Set<MailSnippet>();
    public DbSet<MailSignature> MailSignatures => Set<MailSignature>();
    public DbSet<MailIdentity> MailIdentities => Set<MailIdentity>();

    protected override void OnModelCreating(ModelBuilder model)
    {
        model.Entity<MailAccount>().HasIndex(x => x.NormalizedEmailAddress).IsUnique();
        model.Entity<MailAccount>().Property(x => x.EmailAddress).HasMaxLength(320);
        model.Entity<MailAccount>().Property(x => x.NormalizedEmailAddress).HasMaxLength(320);
        model.Entity<MailCredential>().HasOne(x => x.MailAccount).WithMany(x => x.Credentials).HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailCredential>().HasIndex(x => new { x.MailAccountId, x.AuthenticationMethod }).IsUnique();
        model.Entity<MailSession>().HasOne(x => x.MailAccount).WithMany(x => x.Sessions).HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailSession>().HasIndex(x => x.RefreshTokenHash).IsUnique();
        model.Entity<MailFolder>().HasIndex(x => new { x.MailAccountId, x.FullName }).IsUnique();
        model.Entity<MailFolder>().Property(x => x.Delimiter).HasMaxLength(8);
        model.Entity<MailFolder>().HasOne(x => x.MailAccount).WithMany(x => x.Folders).HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailFolder>().HasOne(x => x.SyncState).WithOne(x => x.MailFolder).HasForeignKey<SyncState>(x => x.MailFolderId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailClient.Domain.Entities.Mail>().HasIndex(x => new { x.MailFolderId, x.Uid }).IsUnique();
        model.Entity<MailClient.Domain.Entities.Mail>().Property(x => x.Subject).HasMaxLength(500);
        model.Entity<MailClient.Domain.Entities.Mail>().Property(x => x.FromAddress).HasMaxLength(320);
        model.Entity<MailClient.Domain.Entities.Mail>().Property(x => x.FromDisplayName).HasMaxLength(250);
        model.Entity<MailClient.Domain.Entities.Mail>().Property(x => x.ToAddress).HasMaxLength(320);
        model.Entity<MailClient.Domain.Entities.Mail>().Property(x => x.MessageId).HasMaxLength(998);
        model.Entity<MailClient.Domain.Entities.Mail>().Property(x => x.InReplyToMessageId).HasMaxLength(998);
        model.Entity<MailClient.Domain.Entities.Mail>().Property(x => x.References).HasMaxLength(4096);
        model.Entity<MailClient.Domain.Entities.Mail>().HasIndex(x => x.MessageId);
        if (Database.IsNpgsql())
        {
            model.Entity<MailClient.Domain.Entities.Mail>()
                .Property<NpgsqlTsVector>("SearchVector")
                .IsGeneratedTsVectorColumn("simple", nameof(MailClient.Domain.Entities.Mail.Subject), nameof(MailClient.Domain.Entities.Mail.BodyText), nameof(MailClient.Domain.Entities.Mail.FromAddress), nameof(MailClient.Domain.Entities.Mail.FromDisplayName), nameof(MailClient.Domain.Entities.Mail.ToAddress), nameof(MailClient.Domain.Entities.Mail.MessageId));
            model.Entity<MailClient.Domain.Entities.Mail>().HasIndex("SearchVector").HasMethod("GIN");
        }
        model.Entity<MailClient.Domain.Entities.Mail>().HasOne(x => x.MailAccount).WithMany(x => x.Mails).HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailClient.Domain.Entities.Mail>().HasOne(x => x.MailFolder).WithMany(x => x.Mails).HasForeignKey(x => x.MailFolderId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailClient.Domain.Entities.Mail>().HasOne(x => x.Conversation).WithMany(x => x.Mails).HasForeignKey(x => x.ConversationId).OnDelete(DeleteBehavior.SetNull);
        model.Entity<MailClient.Domain.Entities.Mail>().HasIndex(x => x.ConversationId);
        model.Entity<Conversation>().Property(x => x.NormalizedSubject).HasMaxLength(500);
        model.Entity<Conversation>().HasIndex(x => new { x.MailAccountId, x.NormalizedSubject });
        model.Entity<Conversation>().HasIndex(x => new { x.MailAccountId, x.LastMessageAt });
        model.Entity<MailParticipant>().HasIndex(x => new { x.MailId, x.Type, x.SortOrder });
        model.Entity<MailParticipant>().Property(x => x.Address).HasMaxLength(320);
        model.Entity<MailParticipant>().Property(x => x.NormalizedAddress).HasMaxLength(320);
        model.Entity<MailParticipant>().Property(x => x.DisplayName).HasMaxLength(250);
        model.Entity<MailParticipant>().HasOne<MailClient.Domain.Entities.Mail>().WithMany(x => x.Participants).HasForeignKey(x => x.MailId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailHeader>().HasIndex(x => new { x.MailId, x.Name });
        model.Entity<MailHeader>().Property(x => x.Name).HasMaxLength(998);
        model.Entity<MailHeader>().Property(x => x.Value).HasMaxLength(4096);
        model.Entity<MailHeader>().HasOne<MailClient.Domain.Entities.Mail>().WithMany(x => x.Headers).HasForeignKey(x => x.MailId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<Attachment>().HasIndex(x => new { x.MailAccountId, x.MailId });
        model.Entity<Attachment>().Property(x => x.FileName).HasMaxLength(255);
        model.Entity<Attachment>().Property(x => x.ContentType).HasMaxLength(150);
        model.Entity<Attachment>().Property(x => x.ContentId).HasMaxLength(998);
        model.Entity<Attachment>().Property(x => x.ContentDisposition).HasMaxLength(20);
        model.Entity<Attachment>().HasOne(x => x.Mail).WithMany(x => x.Attachments).HasForeignKey(x => x.MailId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<Attachment>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<SyncState>().HasIndex(x => x.MailFolderId).IsUnique();
        model.Entity<SyncState>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<SyncSkippedUid>().HasIndex(x => new { x.MailFolderId, x.Uid }).IsUnique();
        model.Entity<SyncSkippedUid>().HasOne<MailFolder>().WithMany().HasForeignKey(x => x.MailFolderId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<SyncSkippedUid>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<SendOperation>().HasIndex(x => new { x.MailAccountId, x.IdempotencyKey }).IsUnique();
        model.Entity<SendOperation>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<DeviceToken>().HasIndex(x => new { x.MailAccountId, x.Token }).IsUnique();
        model.Entity<DeviceToken>().Property(x => x.Token).HasMaxLength(500);
        model.Entity<DeviceToken>().Property(x => x.Platform).HasMaxLength(100);
        model.Entity<DeviceToken>().Property(x => x.AppVersion).HasMaxLength(50);
        model.Entity<DeviceToken>().Property(x => x.Locale).HasMaxLength(35);
        model.Entity<DeviceToken>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<AuditLog>().HasIndex(x => new { x.MailAccountId, x.TimestampUtc });
        // Audit history is deliberately not destroyed with the mailbox: the row survives with a null account id.
        model.Entity<AuditLog>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.SetNull);
        model.Entity<RuntimeConfiguration>().HasKey(x => x.Id);
        model.Entity<RuntimeConfiguration>().Property(x => x.Version).IsConcurrencyToken();
        model.Entity<RuntimeConfiguration>().Property(x => x.SettingsJson).HasColumnType("jsonb");
        model.Entity<OAuthStateNonce>().HasIndex(x => x.NonceHash).IsUnique();
        model.Entity<OAuthStateNonce>().Property(x => x.NonceHash).HasMaxLength(128);
        model.Entity<AllowlistedEmail>().HasIndex(x => x.NormalizedEmail).IsUnique();
        model.Entity<AllowlistedEmail>().Property(x => x.Email).HasMaxLength(320);
        model.Entity<AllowlistedEmail>().Property(x => x.NormalizedEmail).HasMaxLength(320);
        model.Entity<ScheduledSend>().HasIndex(x => new { x.MailAccountId, x.IdempotencyKey }).IsUnique();
        model.Entity<ScheduledSend>().HasIndex(x => new { x.Status, x.SendAtUtc });
        model.Entity<ScheduledSend>().Property(x => x.Subject).HasMaxLength(500);
        model.Entity<ScheduledSend>().Property(x => x.IdempotencyKey).HasMaxLength(200);
        model.Entity<ScheduledSend>().Property(x => x.Status).IsConcurrencyToken();
        model.Entity<ScheduledSend>().Property(x => x.Revision).IsConcurrencyToken();
        model.Entity<ScheduledSend>().HasOne(x => x.MailAccount).WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<ScheduledSendAttachment>().Property(x => x.FileName).HasMaxLength(255);
        model.Entity<ScheduledSendAttachment>().Property(x => x.ContentType).HasMaxLength(150);
        model.Entity<ScheduledSendAttachment>().HasOne(x => x.ScheduledSend).WithMany(x => x.Attachments).HasForeignKey(x => x.ScheduledSendId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailLabel>().HasIndex(x => new { x.MailAccountId, x.Name }).IsUnique();
        model.Entity<MailLabel>().Property(x => x.Name).HasMaxLength(100);
        model.Entity<MailLabel>().HasOne(x => x.MailAccount).WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailRule>().HasOne(x => x.MailAccount).WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailRule>().HasIndex(x => new { x.MailAccountId, x.Priority, x.Id });
        model.Entity<MailRule>().HasIndex(x => new { x.MailAccountId, x.LegacyId }).IsUnique();
        model.Entity<MailRule>().Property(x => x.Name).HasMaxLength(100);
        model.Entity<MailRule>().Property(x => x.Logic).HasMaxLength(3);
        model.Entity<MailRule>().Property(x => x.LegacyId).HasMaxLength(150);
        model.Entity<MailLabelAssignment>().HasIndex(x => new { x.MailAccountId, x.MailId, x.MailLabelId }).IsUnique();
        model.Entity<MailLabelAssignment>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailLabelAssignment>().HasOne<MailClient.Domain.Entities.Mail>().WithMany().HasForeignKey(x => x.MailId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailLabelAssignment>().HasOne<MailLabel>().WithMany().HasForeignKey(x => x.MailLabelId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailSnooze>().HasIndex(x => new { x.MailAccountId, x.MailId }).IsUnique();
        model.Entity<MailSnooze>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailSnooze>().HasOne<MailClient.Domain.Entities.Mail>().WithMany().HasForeignKey(x => x.MailId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<PinnedMail>().HasIndex(x => new { x.MailAccountId, x.MailId }).IsUnique();
        model.Entity<PinnedMail>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<PinnedMail>().HasOne<MailClient.Domain.Entities.Mail>().WithMany().HasForeignKey(x => x.MailId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<Contact>().HasIndex(x => new { x.MailAccountId, x.NormalizedEmail }).IsUnique();
        model.Entity<Contact>().Property(x => x.Email).HasMaxLength(320);
        model.Entity<Contact>().Property(x => x.NormalizedEmail).HasMaxLength(320);
        model.Entity<Contact>().Property(x => x.DisplayName).HasMaxLength(250);
        model.Entity<Contact>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailTemplate>().HasIndex(x => new { x.MailAccountId, x.NormalizedName }).IsUnique();
        model.Entity<MailTemplate>().Property(x => x.Name).HasMaxLength(100);
        model.Entity<MailTemplate>().Property(x => x.NormalizedName).HasMaxLength(100);
        model.Entity<MailTemplate>().Property(x => x.Subject).HasMaxLength(500);
        model.Entity<MailTemplate>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailSnippet>().HasIndex(x => new { x.MailAccountId, x.SortOrder });
        model.Entity<MailSnippet>().Property(x => x.Title).HasMaxLength(100);
        model.Entity<MailSnippet>().Property(x => x.Text).HasMaxLength(2000);
        model.Entity<MailSnippet>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailSignature>().Property(x => x.Name).HasMaxLength(100);
        model.Entity<MailSignature>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailAccount>().HasOne<MailSignature>().WithMany().HasForeignKey(x => x.DefaultNewSignatureId).OnDelete(DeleteBehavior.SetNull);
        model.Entity<MailAccount>().HasOne<MailSignature>().WithMany().HasForeignKey(x => x.DefaultReplySignatureId).OnDelete(DeleteBehavior.SetNull);
        model.Entity<MailAccount>().HasOne<MailSignature>().WithMany().HasForeignKey(x => x.DefaultForwardSignatureId).OnDelete(DeleteBehavior.SetNull);
        model.Entity<MailIdentity>().Property(x => x.EmailAddress).HasMaxLength(320);
        model.Entity<MailIdentity>().Property(x => x.DisplayName).HasMaxLength(250);
        model.Entity<MailIdentity>().Property(x => x.ReplyTo).HasMaxLength(320);
        model.Entity<MailIdentity>().HasOne<MailAccount>().WithMany().HasForeignKey(x => x.MailAccountId).OnDelete(DeleteBehavior.Cascade);
        model.Entity<MailIdentity>().HasOne<MailSignature>().WithMany().HasForeignKey(x => x.SignatureId).OnDelete(DeleteBehavior.SetNull);
        model.Entity<ScheduledSend>().HasOne<MailIdentity>().WithMany().HasForeignKey(x => x.IdentityId).OnDelete(DeleteBehavior.SetNull);
    }
}
