// <auto-generated />
using System;
using MailClient.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailClient.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909120943_InitialMultiAccountSchema")]
    partial class InitialMultiAccountSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailClient.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsInline")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MailId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Mail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FromDisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MailFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "ReceivedAt");

                    b.HasIndex("MailFolderId", "UidValidity", "Uid")
                        .IsUnique();

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImapHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ImapPort")
                        .HasColumnType("integer");

                    b.Property<int>("ImapSecurity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("SaveSentCopy")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<int>("SmtpSecurity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EmailAddress")
                        .IsUnique();

                    b.ToTable("MailAccounts");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FolderType")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsSyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "FullName")
                        .IsUnique();

                    b.ToTable("MailFolders");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastFlagSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastNewMailSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MailFolderId")
                        .HasColumnType("uuid");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MailFolderId")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.Mail", "Mail")
                        .WithMany("Attachments")
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mail");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Mail", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("Mails")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailClient.Domain.Entities.MailFolder", "MailFolder")
                        .WithMany("Mails")
                        .HasForeignKey("MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailAccount", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.User", "User")
                        .WithMany("MailAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailFolder", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("Folders")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SyncState", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailFolder", "MailFolder")
                        .WithOne("SyncState")
                        .HasForeignKey("MailClient.Domain.Entities.SyncState", "MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Mail", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailAccount", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Mails");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailFolder", b =>
                {
                    b.Navigation("Mails");

                    b.Navigation("SyncState");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.User", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("MailAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
