// <auto-generated />
using System;
using MailClient.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace MailClient.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916102401_AddPostgresMailSearch")]
    partial class AddPostgresMailSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailClient.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentDisposition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsInline")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MailId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MailId");

                    b.HasIndex("MailAccountId", "MailId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "TimestampUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "LastMessageAt");

                    b.HasIndex("MailAccountId", "NormalizedSubject");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MailSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "Token")
                        .IsUnique();

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Mail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Answered")
                        .HasColumnType("boolean");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Draft")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ExpectedMailFolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FromDisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("boolean");

                    b.Property<string>("InReplyToMessageId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<DateTime>("InternalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestoreReconciliation")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MailFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<Guid?>("PreviousMailFolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Recent")
                        .HasColumnType("boolean");

                    b.Property<int>("ReconciliationState")
                        .HasColumnType("integer");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Subject", "BodyText", "FromAddress", "FromDisplayName", "ToAddress", "MessageId" });

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MailAccountId");

                    b.HasIndex("MessageId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("MailFolderId", "Uid")
                        .IsUnique();

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthenticationMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscoverySource")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ImapHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImapPort")
                        .HasColumnType("integer");

                    b.Property<int>("ImapSecurity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<bool>("SaveSentCopy")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<int>("SmtpSecurity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmailAddress")
                        .IsUnique();

                    b.ToTable("MailAccounts");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthenticationMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderMetadata")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "AuthenticationMethod")
                        .IsUnique();

                    b.ToTable("MailCredentials");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FolderType")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "FullName")
                        .IsUnique();

                    b.ToTable("MailFolders");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("MailId", "Name");

                    b.ToTable("MailHeaders");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("MailId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MailId", "Type", "SortOrder");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIdentifier")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.ToTable("MailSessions");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SendOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SentCopySaved")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Warning")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("SendOperations");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SyncSkippedUid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MailFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId");

                    b.HasIndex("MailFolderId", "Uid")
                        .IsUnique();

                    b.ToTable("SyncSkippedUids");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastFlagSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastNewMailSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MailAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MailFolderId")
                        .HasColumnType("uuid");

                    b.Property<long>("NextUidScanStart")
                        .HasColumnType("bigint");

                    b.Property<long>("UidValidity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId");

                    b.HasIndex("MailFolderId")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", null)
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailClient.Domain.Entities.Mail", "Mail")
                        .WithMany("Attachments")
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mail");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", null)
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", null)
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Mail", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Mails")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MailClient.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("Mails")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailClient.Domain.Entities.MailFolder", "MailFolder")
                        .WithMany("Mails")
                        .HasForeignKey("MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("MailAccount");

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailCredential", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("Credentials")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailFolder", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("Folders")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailHeader", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.Mail", null)
                        .WithMany("Headers")
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailParticipant", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.Mail", null)
                        .WithMany("Participants")
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailSession", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", "MailAccount")
                        .WithMany("Sessions")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SendOperation", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", null)
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SyncSkippedUid", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", null)
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailClient.Domain.Entities.MailFolder", null)
                        .WithMany()
                        .HasForeignKey("MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailClient.Domain.Entities.SyncState", b =>
                {
                    b.HasOne("MailClient.Domain.Entities.MailAccount", null)
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailClient.Domain.Entities.MailFolder", "MailFolder")
                        .WithOne("SyncState")
                        .HasForeignKey("MailClient.Domain.Entities.SyncState", "MailFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailFolder");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Mails");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.Mail", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Headers");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailAccount", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Folders");

                    b.Navigation("Mails");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MailClient.Domain.Entities.MailFolder", b =>
                {
                    b.Navigation("Mails");

                    b.Navigation("SyncState");
                });
#pragma warning restore 612, 618
        }
    }
}
